services:

  ai-fers:
    image: ai-fers
    hostname: ai-fers
    container_name: ai-fers
    ports:
        - '8000:8000'
    environment:
        - MODEL_PATH=/fers_files/models/model.h5
        - CONFIG_PATH=/fers_files/config/config.json
        - IMAGE_INPUT_DIR=/fers_files/input_images
        - JSON_OUTPUT_DIR=/fers_files/output_json
    volumes:
      - ./docker_volume:/fers_files
