services:

    ai-fers:
        image: ai-fers
        hostname: ai-fers
        container_name: ai-fers
        ports:
            - '8000:8000'
        environment:
            - MODEL_PATH=/fers_files/models/model.h5
            - CONFIG_PATH=/fers_files/config/config.json
            - IMAGE_INPUT_DIR=/fers_files/input_images
            - JSON_OUTPUT_DIR=/fers_files/output_json
        volumes:
          - ${SHARED_VOLUME}:/fers_files

    facial-extraction:
        image: facial-extraction
        hostname: facial_extraction
        container_name: facial_extraction
        ports:
            - '8001:8000'
        environment:
            - IMAGE_INPUT_DIR=/fers_files/input_images
        volumes:
          - ${SHARED_VOLUME}:/fers_files

    fers-bff:
        image: fers-bff:latest
        hostname: fers-bff
        container_name: fers-bff
        restart: always
        ports:
            - 8080:8080
        environment:
            - FILE_STORAGE_DIR=/fers_files/input_images
            - REPORT_STORAGE_DIR=/fers_files/output_json
            - URL_BASE_PREDICTOR=http://ai-fers:8000
        volumes:
          - ${SHARED_VOLUME}:/fers_files
