services:

  facial-extraction:
    image: facial-extraction
    hostname: facial_extraction
    container_name: facial_extraction
    ports:
        - '8001:8000'
    environment:
        - IMAGE_INPUT_DIR=/fers_files/input_images
    volumes:
      - ${SHARED_VOLUME}:/fers_files
